{{- if and .Values.buildkit.enabled .Values.buildkitdCacheMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildkit-service.fullname" . }}-cache-metrics
  namespace: {{ include "buildkit-service.namespace" . }}
  labels:
    {{- include "buildkit-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkitd
data:
  dir-size-exporter.py: |
{{ include "buildkit-service.dirSizeExporterScript" . | indent 4 }}
{{- end }}
