{{- if .Values.packageMirror.enabled }}
{{- $selectedMirrors := include "buildkit-service.packageMirror.selectedRegistryMirrors" . | fromYamlArray -}}
{{- range $selectedMirrors }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildkit-service.packageMirror.fullname" $ }}-registry-{{ .name }}-config
  namespace: {{ include "buildkit-service.packageMirror.namespace" $ }}
  labels:
    {{- include "buildkit-service.packageMirror.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .serviceName }}
type: Opaque
stringData:
  config.yml: |
{{ include "buildkit-service.packageMirror.registryConfig" (dict "root" $ "mirror" .) | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
